#!/bin/bash

docker info > /dev/null 2>&1

# Ensure that Docker is running...
if [ $? -ne 0 ]; then
    echo "Docker is not running."

    exit 1
fi

# php artisan migrate
# php artisan db:seed --class=DemoSeeder

docker run --rm -d \
    --name buy-a-cow \
    -v /"$PWD"://opt/project \
    -w //opt/project \
    -p 8000:8000 \
    php:8.1-cli-alpine \
    php artisan serve --host=0.0.0.0
